language: cpp

addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
        packages:
            - g++-5
            - gcc-5
            - cmake
            - cmake-data
            - valgrind
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

env:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - make
  - cd test
  - valgrind --error-exitcode=1 --leak-check=full ./tests

compiler:
  - gcc
